#!/bin/bash

VMWAREBIN=vmware

if ! command -v $VMWAREBIN &> /dev/null
then
    echo "Command $VMWAREBIN could not be found. Exiting."
    exit
fi

VMWVC=$($VMWAREBIN -v | cut -d' ' -f 3)
VMWARE_VERSION=workstation-$VMWVC
VMWARE_KVERSION=w$VMWVC-k$(uname -r | cut -d'-' -f 1 | head -c 4)

GITHUB_MODULES_ROOT=https://github.com/mkubecek
GITHUB_GIT=$GITHUB_MODULES_ROOT/vmware-host-modules.git
GITHUB_HOST_MODULES=$GITHUB_MODULES_ROOT/vmware-host-modules
GITHUB_MODULES_RELEASE_PAGE=$GITHUB_HOST_MODULES/archive/refs/tags

TMP_FOLDER=/tmp/patch-vmware

################################################################################
# this function is called when Ctrl-C is sent                                  #
################################################################################
function trap_ctrlc ()
{
    Clean
    exit 2
}

# initialise trap to call trap_ctrlc function
# when signal 2 (SIGINT) is received
trap "trap_ctrlc" 2

################################################################################
# Help                                                                         #
################################################################################
Help()
{
    if [ -z "$VMWVC" ]; then
        VMVC_LINK="'$GITHUB_HOST_MODULES'"
    else
        VMVC_LINK="'$GITHUB_HOST_MODULES/tree/$VMWARE_VERSION'-branch"
    fi

    # Display Help
    echo "Use one of the following options to decide how vmware-modules should be installed"
    echo
    echo "Syntax: scriptTemplate [-k|K|-kernel|kernel]"
    echo "options:"
    echo "empty   Download modules from $VMVC_LINK"
    echo "k       Download source from '$GITHUB_MODULES_RELEASE_PAGE' and install it"
    echo
}

Build()
{
    read -p "Modules downloaded. If you want, you can modify them under '$TMP_FOLDER' or press enter to continue ..."
    echo
    echo "Attempt to install vmware-host-modules for $VMWARE_VERSION"
    echo
    make
    sudo make install
    sudo rm /usr/lib/vmware/lib/libz.so.1/libz.so.1
    sudo ln -s /lib/x86_64-linux-gnu/libz.so.1 /usr/lib/vmware/lib/libz.so.1/libz.so.1
    sudo /etc/init.d/vmware restart
    Clean
}

Clean()
{
    if [ -d "$TMP_FOLDER" ]; then
        echo
        echo
        echo "Purge '$TMP_FOLDER' ..."
        rm -fdr $TMP_FOLDER
        echo "Done ..."
        echo
    fi
}

Clean
mkdir -p $TMP_FOLDER
cd $TMP_FOLDER

if [ "$1" = "-h" ]; then
    Help
elif [ "$1" = "-k" ] || [ "$1" = "k" ] || [ "$1" = "-K" ] || [ "$1" = "K" ] || [ "$1" = "-kernel" ] || [ "$1" = "kernel" ] ; then
    echo
    echo "Downloading '$VMWARE_KVERSION' modules"
    echo
    mkdir -p $TMP_FOLDER/vmware-host-modules
    cd $TMP_FOLDER/vmware-host-modules
    wget $GITHUB_MODULES_RELEASE_PAGE/$VMWARE_KVERSION.zip
    unzip $VMWARE_KVERSION.zip
    cd $TMP_FOLDER/vmware-host-modules/vmware-host-modules-$VMWARE_KVERSION
    Build
else
    echo
    echo "Downloading '$VMWARE_VERSION' modules"
    echo "Cloning '$GITHUB_GIT' repo"
    git clone $GITHUB_GIT
    echo
    cd $TMP_FOLDER/vmware-host-modules
    echo "Checkout $VMWARE_VERSION from '$GITHUB_HOST_MODULES'"
    git checkout $VMWARE_VERSION
    git fetch
    echo
    Build
 fi
